### ISSUE TITLE
TimeoutSensorWorker.OnTimeOutListener - onTimeOut called multiple times

### ISSUE THREAD

**Issue by android-dataticket** [OGx09/TimedDog#1]
Trying to test to see what causes this, but there are times when the listener calls onTimeOut twice or more when the timeout duration expires.  

For now it seems to happen more often when the timeout occurs while in the background.

**Comment by devmike01** [comment]
What version of the library are you currently using?

**Comment by android-dataticket** [comment]
> What version of the library are you currently using?

I forked before after your Feb 15, 2020 commits, so I do not have any changes from March 2020 and beyond.

This is so sporadic and hard to recreate on demand, but it does happen.  The dialog I'm displaying to the end-user which is triggered by the onTimeOut interface must only be displayed once.  This dialog allows the end-user to sign out now or stay signed in, and when staying signed in it will start the timeout sensor again.  If the dialog was appeared more than once, they end up clicking the stay signed in button more than once and it ques up multiple timeout sensors - it's a snowball effect.

My bandaid solution is to create an integer and check against it -
```
int timeOutCalled = 0; //this is an activity global variable to be mutable within inner class onTimeOut

timeOutCalled++;
                        Log.e("TimeoutCalled", timeOutCalled + " time(s).");
                        if (timeOutCalled > 1) {
                            Log.e("TimeoutCalled", "More than once!");
                            return;
                        }

```
I only return this integer to 0 if the end-user has selected 'stay signed in' and indeed the timer needs to be set again.

**Comment by devmike01** [comment]
Good for you. I just went through the source code of the library, and it seems the bug has been fixed already. Thank your sharing your solution though

**Comment by android-dataticket** [comment]
Thank you, will test with your latest release and see if anything reoccurs.  Thanks for your work on this one, it's a nice implementation!

**Comment by android-dataticket** [comment]
> Good for you. I just went through the source code of the library, and it seems the bug has been fixed already. Thank you for sharing your solution though

so I noticed a few changes that have results that you may not have been expecting.

You removed the call to init Foreground.java (not sure this matters)
Changed the TimeOut Listener interface to isBackground instead of isForeground (noted...)
Changed the handler call backs in TimedDogWorker.java, and most importantly, do not have any call for action when the app is in the background.. the OnTimeOut is only getting called if the app is in the foreground.  

Please can you take a look?

I fixed by adding a global integer 'BACKGROUND_WHAT' and setting it to call handler.sendEmptyMessage(BACKGROUND_WHAT) in your Result doWork() method of the TimedDogWorker.java:

`               if (TimeoutSensorAppLifecycle.getTimeoutSensorAppLifecycleEvents().isForeground()) {
                    keepInBackground(false);
                    handler.sendEmptyMessage(FOREGROUND_WHAT);
                } else {
                    handler.sendEmptyMessage(BACKGROUND_WHAT);
                    keepInBackground(true);
                }`

**Comment by devmike01** [comment]
I could have handled it that way. But the problem with that implementation is that when another app is on the foreground and your app launches an activity from the background. The activity will forcefully take over the screen from the current app in the foreground. I don't know about you, but that sounds like a nasty behavior to me and on top of that, your users find it annoying. Hence why I'm scheduling the callback immediately after the app is back from the background.

My implementation is very simple and somewhat efficient. It goes this way,

- When the set time has elapsed and the app is in the background, keep a value.
- Immediately the app is in `onResume` state, check the cached value to determine if `OnTimeOutListener` should be called. This is done in a few milliseconds.
- Finally,  clean up the cached value.

**Comment by android-dataticket** [comment]
I did actually see what you were doing here after I wrote my last reply.  I was indeed calling a forceful 'bring-app-to-foreground' intent and I can see how it may be disrupting.

One thing I noticed though, is that there doesn't appear to be anything happening in your newly created onResume lifecycle event.. it appears it's commented out - is this intended?  As it stands now, without any of my forceful foreground modifications, if the timeout occurs in the background, nothing actually happens at all when the app comes to the foreground... see:

`    @OnLifecycleEvent(Lifecycle.Event.ON_RESUME)
    public void onResumeMode(){
        boolean isLogout = timedSharedPreference.getBoolean(TimedDogXWorker.LOGOUT_CHECK, false);
        if (isLogout){
           // TimedDogXWorker.getHandler().get().sendEmptyMessage(FOREGROUND);
            timedSharedPreference.edit().clear().apply();
        }
    }`

**Comment by devmike01** [comment]
It's been handled in `TimedDogXWorker` class, here:

```java
 boolean isBackground = sharedPreferences.getBoolean(LOGOUT_CHECK, false);
            if(isBackground){
                onTimeOutListener.onTimeOut(true);
                Log.d(TAG, "Fired from the background!");
            }
```
Please, fork the project and run the sample app on your device. Then dive deep into the codes to understand how they work.

**Comment by android-dataticket** [comment]
> It's been handled in `TimedDogXWorker` class, here:
> 
> ```java
>  boolean isBackground = sharedPreferences.getBoolean(LOGOUT_CHECK, false);
>             if(isBackground){
>                 onTimeOutListener.onTimeOut(true);
>                 Log.d(TAG, "Fired from the background!");
>             }
> ```
> 
> Please, fork the project and run the sample app on your device. Then dive deep into the codes to understand how they work. Nevertheless, thank you for the observations.

I have forked and run and debugged, the code you mention is being called in  public Builder listener(final OnTimeOutListener onTimeOutListener), which is only called once during the activity onCreate which builds the sensor, and not being called when the timeout occurs.. I could be missing something?

**Comment by devmike01** [comment]
I thought I have explained how the callback works earlier. Anyways, I'll try explaining it one more time. When the activity that builds the `Timedog` get called, it registered the callback and keep it in the memory as long as the activity is not destroyed - to understand this, read more on Activity Lifecycle. 

When the app goes to the background and returns to the foreground, the activity still have a reference to `Timedog` in the memory, thus, no need to recreate it. The value that was kept when the app was going to the background is checked, and if it's `true` the callback will be triggered, otherwise, it waits until the time elapsed on the foreground. Refer to this https://github.com/devmike01/TimedDog/issues/1#issuecomment-626819295

No new bug has been found yet on this new release, hence I'm going to close this issue. Feel free to open it if you encounter any error why using the new release.

**Comment by android-dataticket** [comment]
My bad, I guess that explains it.  I'm building this in the login activity of the app, which is shortly afterwards destroyed as it moves into the main activity.. thanks for your time

**Comment by devmike01** [comment]
> My bad, I guess that explains it. I'm building this in the login activity of the app, which is shortly afterwards destroyed as it moves into the main activity.. thanks for your time

I see what you meant now. I'm looking into it already, and I'm going to reopen this issue again. Thank you for feedback.

**Comment by OGx09** [comment]
Hi, this issue has been resolved. Please check out the latest update.
