### ISSUE TITLE
java.util.concurrent.CancellationException: Task was cancelled.

### ISSUE THREAD

**Issue by android-dataticket** [OGx09/TimedDog#2]
It appears that there's a 10 minute limit on the Work Library if the app is in the background.

Set the timeout to 15 minutes, you'll see the WorkerWrapper cancel at 10 minutes and restart counting down again from 15 minutes, never reaching the actual onTimeOut if the app remains in the background the entire time.

This is also what appears to be causing multiple worker threads starting which call onTimeOut multiple times when finally able to expire

**Comment by android-dataticket** [comment]
https://developer.android.com/topic/libraries/architecture/workmanager/advanced/long-running has information on making the worker thread an important 'long-running' worker thread

**Comment by devmike01** [comment]
You've been so helpful with constructive criticisms. I love it. I'm refactoring the entire code base to improve the library and also fix the bugs that were pointed out. Please when feel free to point out as many bugs as possible. Thank you

**Comment by OGx09** [comment]
Hi @android-dataticket , sorry it took me a while to get back. I have been busy. All issues that were raised have been fixed. Please check out the documentation on the homepage to see the latest version. I will not close this issue.
